## 00. Pytorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("PyTorch Version:", torch.__version__)

PyTorch Version: 2.10.0+cu130


## Introduction to Tensors

### Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# scalar number of dimension
scalar.ndim

0

In [4]:
# get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
# get number of dimension for vector
vector.ndim

1

In [7]:
# shape of vector
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# number of dims for matrix
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [12]:
# number of dims in tensor
TENSOR.ndim

3

In [13]:
# shape of tensor
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

In [14]:
# Create random tensors of shape (3, 4)
random_tensor = torch.rand(7, 3, 4)
random_tensor

tensor([[[2.7814e-01, 2.6615e-01, 2.1394e-01, 5.1181e-01],
         [7.3902e-01, 3.9488e-01, 5.2123e-02, 5.5777e-01],
         [2.0805e-01, 6.7805e-01, 3.2251e-01, 9.7936e-01]],

        [[3.1387e-02, 2.8615e-02, 6.4718e-03, 1.0445e-02],
         [2.4420e-01, 9.1465e-01, 5.9585e-01, 2.0840e-01],
         [8.8973e-01, 9.9895e-01, 8.3089e-05, 1.3382e-01]],

        [[3.0405e-01, 7.9097e-01, 2.7689e-01, 7.1491e-01],
         [7.3095e-01, 8.8186e-01, 7.4624e-02, 6.5374e-01],
         [5.9878e-01, 4.8103e-01, 1.1704e-01, 8.7283e-01]],

        [[8.3982e-01, 8.4437e-01, 6.7352e-01, 8.7697e-01],
         [4.9365e-01, 3.7000e-01, 3.3305e-01, 8.3962e-01],
         [6.1462e-01, 3.4898e-02, 3.1559e-01, 8.2081e-01]],

        [[8.5328e-01, 5.6778e-01, 1.3962e-01, 8.1583e-01],
         [2.9608e-01, 3.4745e-01, 8.9072e-01, 4.3536e-01],
         [5.2171e-01, 2.2190e-01, 3.1119e-01, 6.2059e-01]],

        [[4.9188e-02, 3.2491e-01, 9.5662e-01, 5.3593e-01],
         [4.7164e-01, 9.7160e-01, 6.3037e-01, 

In [15]:
random_tensor.ndim

3

In [16]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [17]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [19]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# use torch.range()
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [23]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [24]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

## Manipulating Tensors (tensor operations)

In [28]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [30]:
tensor

tensor([1, 2, 3])

In [31]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [32]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

In [33]:
# element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [34]:
# matrix multiplication
print(tensor, "*", tensor)
print(f"Equals: {torch.matmul(tensor, tensor)}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: 14


### Matrix Product Vs Element-Wise Product

In [35]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 2 ms


In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [37]:
try:
    torch.matmul(torch.rand((3, 2)), torch.rand((3, 2)))
except Exception as e:
    print("Error:", e)

Error: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


### Tensor Aggregation Operations

In [38]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [40]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [41]:
# find the mean - note: the torch.mean() functions requires a tensor of type float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [42]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [43]:
# argmax and argmin
torch.argmax(x), torch.argmin(x)

(tensor(9), tensor(0))

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueeze - Add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [44]:
# create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
# Add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [46]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
# changing z, changes x, because a view of a tensor shares same memory as the original tensor
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [48]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [49]:
# squeeze
torch.squeeze(x)

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

## Indexing (Selecting Data From Tensor)

In [50]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [51]:
# indexing on this new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [52]:
# index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [53]:
# index on last dimension
x[0][0][0]

tensor(1)

In [54]:
# use ":" to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [55]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

## PyTorch Tensors and Numpy

In [56]:
# numpy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # creating tensor from existing np array, inherits the dtype of the array
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [57]:
tensor.dtype

torch.float64

In [58]:
# change value of array, what will it do to the "tensor"?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [59]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [60]:
print("Tensor:", tensor)
print("Numpy Tensor:", numpy_tensor)

Tensor: tensor([1., 1., 1., 1., 1., 1., 1.])
Numpy Tensor: [1. 1. 1. 1. 1. 1. 1.]
